// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadeMedicoApi.Data;

namespace cadeMedicoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PR",
                            Nome = "Londrina"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PR",
                            Nome = "Cambé"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "PR",
                            Nome = "Apucarana"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "SP",
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "PR",
                            Nome = "Rolandia"
                        },
                        new
                        {
                            Id = 6,
                            Estado = "PR",
                            Nome = "Maringa"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cardiologista"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Clinico Geral"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Podologista"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Neurologista"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Pediatra"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Psiquiatra"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 6,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 5
                        },
                        new
                        {
                            MedicoId = 6,
                            CidadeId = 6
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 5
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 4
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 5,
                            EspecialidadeId = 2
                        },
                        new
                        {
                            MedicoId = 6,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 1
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "000000",
                            Nome = "Ana Paula",
                            Telefone = "33330000"
                        },
                        new
                        {
                            Id = 2,
                            Crm = "111111",
                            Nome = "Juliana",
                            Telefone = "33331111"
                        },
                        new
                        {
                            Id = 3,
                            Crm = "222222",
                            Nome = "Paulo",
                            Telefone = "33332222"
                        },
                        new
                        {
                            Id = 4,
                            Crm = "333333",
                            Nome = "João",
                            Telefone = "33333333"
                        },
                        new
                        {
                            Id = 5,
                            Crm = "444444",
                            Nome = "Marcio",
                            Telefone = "33334444"
                        },
                        new
                        {
                            Id = 6,
                            Crm = "666666",
                            Nome = "Camila",
                            Telefone = "33335555"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrivilegioModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Master"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "User"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "user_ana",
                            Nome = "Ana Paula",
                            PrivilegioId = 1,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 2,
                            Login = "user_juliana",
                            Nome = "Juliana",
                            PrivilegioId = 2,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 3,
                            Login = "user_paulo",
                            Nome = "Paulo",
                            PrivilegioId = 2,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 4,
                            Login = "user_joao",
                            Nome = "João",
                            PrivilegioId = 2,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 5,
                            Login = "user_marcio",
                            Nome = "Marcio",
                            PrivilegioId = 3,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 6,
                            Login = "user_camila",
                            Nome = "Camila",
                            PrivilegioId = 3,
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.HasOne("cadeMedicoApi.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("cadeMedicoApi.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidade");
                });
#pragma warning restore 612, 618
        }
    }
}
